services:
  polymarket-pipeline:
    build: .
    container_name: polymarket_pipeline
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 9G
    volumes:

      - ~/data-cache/polymarket_cache:/app/data

      - ~/data-cache/polymarket_cache:/app/polymarket_cache

      - ~/config.py:/app/config.py

      - ~/sim_strat_3.py:/app/sim_strat_5.py
      
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
