import pandas as pd
import re

# 1. Paste the FINAL V5 LLM_FEATURES dictionary here
LLM_FEATURES = {
    "topic_categories": {
        "cryptocurrency_markets": ["btc/usdt 1 hour candle", "eth/usd data stream", "sol/usdt 1 minute candle", "xrp/usd data stream", "binance 1 minute candle", "chainlink data stream", "bitcoin up or down", "solana up or down", "ethereum network gas fee", "coinbase listing announcement", "crypto market capitalization", "tether usdt depeg", "btc/usd", "eth/usdt", "spot markets", "candle will be used", "binance close prices", "xrp up or down", "sol/usd", "coingecko price", "coinmarketcap data", "candlestick", "all-time high", "ethereum gas", "bitcoin halving", "trading volume", "spot etf", "coinbase listing", "on-chain", "smart contract", "binance spot", "coinbase pro", "ethereum price", "bitcoin price", "solana price", "all-time high btc", "candlestick close", "1h candle", "1d candle", "satoshi", "coingecko api", "bitcoin etf flows", "spot btc etf", "ethereum etf approval", "grayscale bitcoin trust", "gbtc outflows", "blackrock ishares", "fidelity wise origin", "ark 21shares", "sec etf approval", "spot ether etf", "exchange traded fund", "etf net inflows", "usdt pair", "1m candles", "spot exchange rate", "ethereum etf flows", "bitcoin etf outflows", "net asset value", "authorized participant", "aum growth", "s-1 registration", "19b-4 filing", "grayscale trust", "fiat gateway", "mainnet launch event", "testnet deployment phase", "airdrop snapshot block", "token generation event date", "network hard fork", "protocol upgrade implementation", "smart contract audit passed", "total value locked metric", "layer-2 scaling solution", "staking yield percentage"],
        "us_domestic_elections": ["new jersey governor election", "associated press definitive call", "electoral college votes", "presidential nominee primary", "gubernatorial race winner", "senate majority control", "house of representatives seat", "voter turnout percentage", "republican national convention", "democratic national convention", "swing state polling average", "presidential election winner", "popular vote margin", "swing state outcome", "republican presidential nominee", "democratic presidential nominee", "house of representatives control", "gubernatorial race", "primary election results", "turkey pardon ceremony", "congressional hearing testimony", "supreme court ruling", "executive order signed", "state of the union address", "bill signed into law", "cabinet confirmation vote", "impeachment articles", "veto override", "filibuster rule change", "senate confirmation", "campaign finance", "presidential debate", "gubernatorial election", "primary ballot", "press conference announced", "swing states", "gop nominee", "democratic nominee", "iowa caucuses", "new hampshire primary", "super tuesday", "senate majority", "swing state polls", "electoral votes", "presidential debate stage", "inauguration day", "ballot access deadline", "national polling average", "early voting turnout", "senate confirmation hearing", "house of representatives floor", "speaker of the house gavel", "veto override vote", "bipartisan infrastructure bill", "budget reconciliation process", "congressional district map", "midterm election cycle", "committee subpoena"],
        "global_sovereign_elections": ["prime minister of the united kingdom", "french national assembly election", "indian lok sabha majority", "european parliament seats", "canadian federal election", "australian federal election", "brazilian presidential runoff", "mexican general election winner", "south african anc majority", "german bundestag coalition", "japanese ldp leadership"],
        "basketball_markets": ["nba game scheduled for", "western conference finals", "eastern conference finals", "nba finals mvp", "total points rebounds assists", "nba regular season mvp", "nba draft first overall", "lakers vs celtics", "three point field goals made", "flagrant foul assessed", "nba play-in tournament", "rebounds o/u", "assists during the game", "points o/u", "records more than", "steals plus blocks", "triple double", "first basket scorer", "turnovers o/u", "points plus rebounds", "combine to score", "over if the", "under if the", "total points", r"o/u 152\.5", r"o/u 239\.5", "combined total is less than", "total score including overtime", "first half total", "second half total", "1h spread", "win the game by", "cover the spread", "against the spread", "spread cover", "favorite to win by", "underdog to lose by less than", "point differential", "margin of victory", "alternative spread", "cbb game", "free throws", "three-pointers", "rebound total", "assists over", "playoff series", "march madness", "ncaa tournament", "shot clock", "buzzer beater", "nba game", "assists o/u", "triple-double", "lebron james", "stephen curry", "nikola jokic", "draymond green", "nba finals", "free throws made", "three-pointers made", "blocks o/u", "final four", "elite eight", "sweet sixteen", "college basketball rankings", "ap top 25 men's", "acc tournament", "big east tournament", "sec tournament", "wooden award", "triple-double recorded", "offensive rebounds gathered", "defensive rebounds secured", "assists per game average", "nba playoffs series", "three-point field goals made", "shot clock violation"],
        "american_football": ["nfl game", "receiving yards", "passing touchdowns", "super bowl", "interception thrown", "rushing attempts", "field goal", "point spread", "afc championship", "nfc championship", "two-point conversion", "sack total", "fumble recovery", "super bowl lviii", "patrick mahomes", "passing yards o/u", "rushing touchdowns", "lombardi trophy", "nfl draft first overall", "aaron rodgers", "nfl regular season", "cfb game", "college football playoff", "cfp national championship", "heisman trophy", "sec championship game", "big ten championship", "rose bowl game", "sugar bowl", "orange bowl", "cotton bowl", "fiesta bowl", "peach bowl", "touchdown pass thrown", "rushing yards accumulated", "super bowl mvp", "field goal attempt made", "interception thrown by", "passing yards total", "point after touchdown converted", "two-point conversion successful", "quarterback sack recorded"],
        "tennis_matches": ["wta", "atp tour", "grand slam", "australian open", "wimbledon", "tiebreak", "straight sets", "match tie-break", "double fault", "service game", "first serve percentage", "match o/u", "roland garros", "wta tour", "grand slam title", "wimbledon final", "us open tennis", "set 1 winner", "tiebreak in match", "straight sets victory", "novak djokovic", "carlos alcaraz", "iga swiatek"],
        "baseball_mlb_markets": ["official final score published on mlb.com", "number of innings completed", "world series champion", "american league pennant", "national league pennant", "mlb home run derby", "cy young award winner", "mlb regular season mvp", "shohei ohtani home runs", "strikeouts recorded by starting pitcher", "mlb wild card series"],
        "soccer_and_football": ["africa cup of nations game", "uefa champions league final", "fifa world cup winner", "english premier league title", "la liga championship", "copa america knockout stage", "ballon d'or recipient", "total goals scored o/u", "yellow cards issued", "penalty kick awarded", "var review overturn", "first 90 minutes of regular play", "stoppage time", "premier league match", "la liga fixture", "goals scored by", "yellow cards drawn", "corner kicks awarded", "penalty shootout result", "clean sheet kept", "mls soccer", "champions league", "red card", "var decision", "fa cup", "bundesliga", "uefa", "serie a standings", "fifa world cup", "ballon d'or", "combine to score 4 or more goals", "fa cup final", "lionel messi", "cristiano ronaldo", "striker to score"],
        "hockey_match_outcomes": ["overtime periods and shootouts", "puck line", "stanley cup playoffs", "nhl regular season", "goals scored in regulation", "empty net goal", "power play goals", "shots on goal o/u", "first period winner", "total goals o/u", "penalty kill", "faceoff win", "hat trick", "goaltender save", "icing call", "blue line", "nhl game", "power play goal", "empty netter", "connor mcdavid", "auston matthews", "vezina trophy", "hart memorial trophy", "nhl eastern conference", "nhl western conference", "nhl game scheduled", "overtime periods considered", "stanley cup finals", "puck line spread", "penalty kill percentage", "faceoff win rate", "empty net goal scored", "goals against average", "shootout winner"],
        "golf_championships": ["baycurrent classic", "pga tour event", "masters tournament green jacket", "us open golf championship", "the open championship claret jug", "pga championship winner", "ryder cup points", "hole in one recorded", "cut line score", "fedex cup playoffs", "liv golf invitational", "liv riyadh event", "myrtle beach classic", "bogey free", "fairways hit", "greens in regulation", "stroke play", "sudden death playoff", "tee time"],
        "macroeconomic_indicators": ["consumer price index cpi release", "federal reserve interest rate decision", "fomc meeting statement", "basis point rate hike", "us inflation rate yoy", "nonfarm payrolls report bls", "bureau of labor statistics data", "us gdp growth rate annualized", "ecb interest rate announcement", "bank of england base rate", "unemployment rate percentage", "cpi print", "inflation rate release", "nonfarm payrolls report", "unemployment rate data", "gdp growth estimate", "retail sales figures", "consumer sentiment index", "producer price index", "jobless claims weekly", "wage growth percentage", "interest rate cut", "basis points hike", "jerome powell press conference", "federal funds rate target", "quantitative tightening", "dot plot projections", "discount window rate", "balance sheet runoff", "emergency rate decision", "sovereign debt", "recession declaration", "treasury yield", "central bank", "cpi report", "consumer price index", "federal reserve rate cut", "basis points bps", "inflation rate yoy", "jerome powell speech", "fed funds rate", "fomc meeting minutes", "gross domestic product", "jobless claims report", "inflation targeting"],
        "corporate_actions": ["earnings report release", "revenue estimate beat", "eps miss", "stock split announcement", "merger acquisition closure", "dividend yield change", "share buyback program", "ceo resignation", "bankruptcy filing chapter", "ipo pricing", "q1 earnings report", "q2 earnings report", "q3 earnings report", "q4 earnings report", "merger and acquisition", "antitrust lawsuit", "initial public offering ipo", "revenue guidance"],
        "social_media_metrics": ["post counter figure", "xtracker.io data", "youtube video views", "twitter followers count", "instagram likes total", "tiktok follower growth", "elon musk tweet replies", "trending topic hashtag", "channel subscriber milestone", "retweet volume"],
        "pop_culture_and_awards": ["box office opening weekend gross", "academy award for best picture", "grammy award for album of the year", "spotify global top 50 chart", "youtube 24 hour view count", "billboard hot 100 number one", "oscars best actor nominee", "emmy award outstanding drama", "rotten tomatoes critics consensus", "metacritic average critic score", "golden globe winner", "domestic box office totals", "worldwide gross revenue", "rotten tomatoes audience score", "streaming viewership hours", "box office mojo data", "theatrical release date", "box office gross", "grammy nomination", "emmy winner", "film festival", "ticket sales", "time person of the year", "best picture oscar", "golden globes", "emmy awards", "taylor swift eras tour", "mcu phase", "academy awards", "oscar for best picture", "grammy for album of the year", "emmy nominations announced", "golden globe recipient", "box office gross revenue", "opening weekend sales", "rotten tomatoes critic score", "metacritic rating average", "academy award winner"],
        "aerospace_and_exploration": ["spacex starship orbital launch attempt", "nasa artemis mission schedule", "falcon 9 launch success", "james webb space telescope image", "isro chandrayaan lunar mission", "crewed mission to mars timeline", "blue origin new shepard flight", "virgin galactic commercial spaceflight", "lunar lander touchdown confirmation", "international space station crew rotation", "orbital payload deployment", "orbit reached successfully", "falcon 9 booster landing", "nasa mission crew", "international space station docking", "lunar surface landing", "mars rover deployment", "satellite deployment confirmed", "suborbital flight completed", "rocket stage separation", "orbital insertion", "iss resupply", "booster recovery", "satellite constellation", "nasa artemis", "super heavy booster", "orbital flight test", "orbital space launch", "low earth orbit reached", "payload successfully deployed", "crewed mars mission", "lunar landing module", "international space station docked", "starship super heavy", "rocket booster recovered", "splashdown confirmed"],
        "climate_and_weather": ["national hurricane center nhc advisory", "saffir-simpson hurricane wind scale category", "noaa global surface temperature", "world meteorological organization wmo report", "hottest year on record confirmation", "atlantic hurricane season named storms", "category 5 hurricane landfall", "arctic sea ice minimum extent", "celsius above pre-industrial levels", "el nino southern oscillation enso", "usgs earthquake magnitude", "temperature anomaly", "rainfall total", "wildfire containment", "carbon emissions", "sea level rise", "heat wave", "tornado warning", "polar vortex", "drought index", "noaa hurricane prediction", "saffir-simpson scale", "named storm", "cat 5 hurricane", "heatwave record", "record high temperature", "national weather service", "hurricane category classification", "maximum sustained winds", "landfall location coordinates", "celsius temperature anomaly", "atmospheric pressure millibars", "millimetres of rainfall", "tropical cyclone path", "heat wave duration", "drought condition index"],
        "geopolitics_and_conflict": ["un security council resolution vote", "nato article 5 invocation", "ceasefire agreement officially signed", "territorial control of region", "deployment of foreign military forces", "international criminal court arrest warrant", "geneva convention violation accusation", "diplomatic relations normalized agreement", "bilateral peace treaty ratification", "un general assembly emergency session", "economic sanctions imposed", "intercepted missile", "surface-to-air", "municipality territory", "border skirmish", "military aid", "drone strike", "peace treaty", "naval blockade", "troop deployment", "un security council resolution", "nato membership", "bilateral treaty", "g7 summit", "brics expansion", "border dispute", "israeli military", "law enforcement personnel", "physically board any vessel", "demilitarized zone", "ground invasion", "diplomatic relations severed", "peace treaty signed", "armed conflict escalation"],
        "artificial_intelligence": ["openai gpt-5 public release", "anthropic claude model update", "google gemini ultra access", "apple mixed reality headset launch", "nvidia earnings report revenue beat", "artificial general intelligence agi achieved", "turing test passed conclusively", "sam altman ceo tenure", "open source llm parameter count", "chatgpt plus active subscribers", "ai regulatory legislation passed", "grok 4.20", "xai", "gpt-4", "openai api", "benchmark score", "open source release", "language model", "context window", "agi prediction", "compute cluster", "neural network", "openai chatgpt", "gpt-5 release", "google gemini advanced", "llm benchmark", "nvidia h100", "ai safety summit", "transformer model parameters"],
        "legal_and_judicial": ["supreme court of the united states scotus opinion", "criminal indictment unsealed document", "guilty verdict formally reached", "department of justice doj lawsuit filing", "sec vs ripple labs ruling", "federal judge injunction granted", "extradition treaty officially invoked", "class action lawsuit final settlement", "appeals court overturns decision", "temporary restraining order tro issued", "subpoena compliance deadline", "scotus decision", "majority opinion authored", "strike down legislation", "writ of certiorari", "dissenting opinion filed", "federal appellate court", "criminal trial verdict", "grand jury indictment", "plea deal accepted", "preliminary injunction granted"],
        "esports_and_gaming": ["league of legends world championship final", "cs:go major tournament grand final", "dota 2 the international aegis", "valorant champions tour vct winner", "twitch peak concurrent viewership", "steam concurrent players all-time record", "the game awards goty recipient", "call of duty league cdl championship", "evo championship series top 8", "overwatch league grand finals mvp", "rocket league championship series rlcs", "liquipedia.net", "sofascore.com/esports", "maps in this series", "league of legends match", "cs:go tournament", "dota 2 international", "first blood drawn", "baron nashor killed", "towers destroyed", "best of three series", "counter-strike match", "map 2", "valorant", "bomb plant", "hltv rating", "frag total", "major championship", "map advantage secured", "dragon soul claimed", "defuse the bomb", "plant the c4", "nexus destroyed", "best-of-five series format", "upper bracket finals"]
    }
}

def run_diagnostics(file_path):
    print(f"📦 Loading Data from {file_path}...")
    
    # Load unique markets (dropping the trade data noise)
    df = pd.read_parquet(file_path, columns=['id', 'question', 'description'])
    df = df.drop_duplicates(subset=['id']).copy()
    
    # Combine question and description into one lowercased text blob
    df['text'] = df['question'].fillna('') + " " + df['description'].fillna('')
    df['text'] = df['text'].str.lower()
    
    total_markets = len(df)
    print(f"📊 Total Unique Markets: {total_markets}")
    
    # Compile regexes using the fast OR operator
    compiled_topics = {
        cat: re.compile(r"|".join(phrases), re.IGNORECASE) 
        for cat, phrases in LLM_FEATURES['topic_categories'].items()
    }
    
    print("🔍 Applying Regex Tags...")
    
    # Track which rows get tagged
    df['has_topic'] = False
    topic_counts = {}
    
    # Vectorized check across the entire dataframe
    for category, pattern in compiled_topics.items():
        hits = df['text'].str.contains(pattern, regex=True)
        topic_counts[category] = hits.sum()
        df['has_topic'] = df['has_topic'] | hits
        
    # Calculate Results
    tagged_count = df['has_topic'].sum()
    untagged_count = total_markets - tagged_count
    coverage_ratio = (tagged_count / total_markets) * 100
    
    print("\n" + "="*50)
    print(f"🎯 COVERAGE RESULTS")
    print("="*50)
    print(f"Total Markets:    {total_markets}")
    print(f"Tagged Markets:   {tagged_count}")
    print(f"Orphan Markets:   {untagged_count}")
    print(f"COVERAGE RATIO:   {coverage_ratio:.2f}%\n")
    
    print("📈 TOPIC DISTRIBUTION")
    print("-" * 50)
    # Sort dict by highest hits
    sorted_topics = sorted(topic_counts.items(), key=lambda x: x[1], reverse=True)
    for category, count in sorted_topics:
        percentage = (count / total_markets) * 100
        print(f"{category:<30} | {count:>7} ({percentage:>5.2f}%)")
        
    print("\n" + "="*50)
    print(f"👻 SAMPLE OF UNTAGGED 'ORPHAN' MARKETS")
    print("="*50)
    
    orphans = df[~df['has_topic']]
    if not orphans.empty:
        # Print up to 10 random orphans
        sample_size = min(10, len(orphans))
        sample = orphans.sample(sample_size)
        for _, row in sample.iterrows():
            q = str(row['question']).replace('\n', ' ')
            print(f"- {q[:120]}...")
    else:
        print("Wow! 100% Coverage Achieved!")

if __name__ == "__main__":
    run_diagnostics("gamma_markets_all_tokens.parquet")
